//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatjesImager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// NI-DAQmx device name of the board generating the sheet (X-mirror) waveforms
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("NI-DAQmx device name of the board generating the sheet (X-mirror) waveforms")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dev1")]
        public string SheetBoard {
            get {
                return ((string)(this["SheetBoard"]));
            }
            set {
                this["SheetBoard"] = value;
            }
        }
        
        /// <summary>
        /// NI-DAQmx device name of the board generating the z (Y-mirror and piezo) waveforms and the camera trigger
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("NI-DAQmx device name of the board generating the z (Y-mirror and piezo) waveforms" +
            " and the camera trigger")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dev2")]
        public string ZAndCamBoard {
            get {
                return ((string)(this["ZAndCamBoard"]));
            }
            set {
                this["ZAndCamBoard"] = value;
            }
        }
        
        /// <summary>
        /// Analog output on the sheet board driving the X-mirror of scan-head 1
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Analog output on the sheet board driving the X-mirror of scan-head 1")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ao0")]
        public string Sheet1Channel {
            get {
                return ((string)(this["Sheet1Channel"]));
            }
            set {
                this["Sheet1Channel"] = value;
            }
        }
        
        /// <summary>
        /// Analog output on the sheet board driving the X-mirror of scan-head 2
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Analog output on the sheet board driving the X-mirror of scan-head 2")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ao2")]
        public string Sheet2Channel {
            get {
                return ((string)(this["Sheet2Channel"]));
            }
            set {
                this["Sheet2Channel"] = value;
            }
        }
        
        /// <summary>
        /// Analog output on the z/camera board driving the Y-mirror (z) of scan-head 1
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Analog output on the z/camera board driving the Y-mirror (z) of scan-head 1")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ao1")]
        public string Z1Channel {
            get {
                return ((string)(this["Z1Channel"]));
            }
            set {
                this["Z1Channel"] = value;
            }
        }
        
        /// <summary>
        /// Analog output on the z/camera board driving the Y-mirror (z) of scan-head 2
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Analog output on the z/camera board driving the Y-mirror (z) of scan-head 2")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ao2")]
        public string Z2Channel {
            get {
                return ((string)(this["Z2Channel"]));
            }
            set {
                this["Z2Channel"] = value;
            }
        }
        
        /// <summary>
        /// Analog output on the z/camera board driving the objective piezo
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Analog output on the z/camera board driving the objective piezo")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ao0")]
        public string PiezoChannel {
            get {
                return ((string)(this["PiezoChannel"]));
            }
            set {
                this["PiezoChannel"] = value;
            }
        }
        
        /// <summary>
        /// Counter on the z/camera board generating the camera frame trigger
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Counter on the z/camera board generating the camera frame trigger")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ctr0")]
        public string CameraTriggerCounter {
            get {
                return ((string)(this["CameraTriggerCounter"]));
            }
            set {
                this["CameraTriggerCounter"] = value;
            }
        }
        
        /// <summary>
        /// Terminal on the z/camera board to which the camera trigger is exported
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Terminal on the z/camera board to which the camera trigger is exported")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PFI0")]
        public string CameraTriggerTerminal {
            get {
                return ((string)(this["CameraTriggerTerminal"]));
            }
            set {
                this["CameraTriggerTerminal"] = value;
            }
        }
        
        /// <summary>
        /// Lower limit of the analog output range of all mirror channels
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Lower limit of the analog output range of all mirror channels")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5")]
        public double MirrorMinVolts {
            get {
                return ((double)(this["MirrorMinVolts"]));
            }
            set {
                this["MirrorMinVolts"] = value;
            }
        }
        
        /// <summary>
        /// Upper limit of the analog output range of all mirror channels
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Upper limit of the analog output range of all mirror channels")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double MirrorMaxVolts {
            get {
                return ((double)(this["MirrorMaxVolts"]));
            }
            set {
                this["MirrorMaxVolts"] = value;
            }
        }
        
        /// <summary>
        /// Control voltage corresponding to the full piezo travel (output range is 0 to this value)
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Control voltage corresponding to the full piezo travel (output range is 0 to this" +
            " value)")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double PiezoMaxVolts {
            get {
                return ((double)(this["PiezoMaxVolts"]));
            }
            set {
                this["PiezoMaxVolts"] = value;
            }
        }
        
        /// <summary>
        /// Full travel of the objective piezo in microns
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Full travel of the objective piezo in microns")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("450")]
        public double PiezoRangeMicrons {
            get {
                return ((double)(this["PiezoRangeMicrons"]));
            }
            set {
                this["PiezoRangeMicrons"] = value;
            }
        }
        
        /// <summary>
        /// Serial number of the Thorlabs PPC001 piezo controller
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Serial number of the Thorlabs PPC001 piezo controller")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("44506384")]
        public string PiezoSerialNumber {
            get {
                return ((string)(this["PiezoSerialNumber"]));
            }
            set {
                this["PiezoSerialNumber"] = value;
            }
        }
        
        /// <summary>
        /// Number of analog output samples generated per camera frame
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Number of analog output samples generated per camera frame")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int SamplesPerFrame {
            get {
                return ((int)(this["SamplesPerFrame"]));
            }
            set {
                this["SamplesPerFrame"] = value;
            }
        }
        
        /// <summary>
        /// Number of sheet sweeps (full triangle cycles) per camera frame
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Number of sheet sweeps (full triangle cycles) per camera frame")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int SweepsPerFrame {
            get {
                return ((int)(this["SweepsPerFrame"]));
            }
            set {
                this["SweepsPerFrame"] = value;
            }
        }
        
        /// <summary>
        /// AO task buffer size as a multiple of the samples generated per write
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("AO task buffer size as a multiple of the samples generated per write")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int AOBufferMultiplier {
            get {
                return ((int)(this["AOBufferMultiplier"]));
            }
            set {
                this["AOBufferMultiplier"] = value;
            }
        }
        
        /// <summary>
        /// Smoothing window of the sheet triangle turn-arounds as a fraction of the sweep period
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Smoothing window of the sheet triangle turn-arounds as a fraction of the sweep pe" +
            "riod")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double SheetTurnAround {
            get {
                return ((double)(this["SheetTurnAround"]));
            }
            set {
                this["SheetTurnAround"] = value;
            }
        }
        
        /// <summary>
        /// Fraction of each piezo sawtooth period spent on the rising (imaging) flank
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Fraction of each piezo sawtooth period spent on the rising (imaging) flank")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public double PiezoSawtoothShape {
            get {
                return ((double)(this["PiezoSawtoothShape"]));
            }
            set {
                this["PiezoSawtoothShape"] = value;
            }
        }
    }
}
